### PR TITLE
Write main readme

### LINKED ISSUE #10: Add main README and organise the docs/ subfolder
We need to have the main README file, a primary contact point for anyone not familiar with the work package. It should link to:
* List of deliverables, tasks and milestones of the work package
* The existing description of D4.2
* Other pages

### PR DESCRIPTION
**Pull request by tskir**
@kauralasoo, @shukapoo: this PR is mostly trivial and covers just the docs, so it's up to you whether to actually review it. Alternatively I can just merge it right away.

I wrote the skeleton of a primary README for the repository and included a succinct table listing all _high-level_ components of our work package. I define _components_ as actual meaningful things we're doing, as opposed to bureaucratic “tasks”, “deliverables” and “milestones”, which can be quite confusing (I know they've definitely been confusing for me).

Added a page linking _all_ components/tasks/subtasks/subsubtasks/deliverables/milestones together for future reference. The information is taken from the spreadsheet in CINECA Google Drive, but over there it's not easy to read at all.

Reorganised documentation files in a separate `docs/` subfolder.

Closes #10.

### CODE REVIEW

**Comment by tskir** [comment]
Rather than reading the diffs, perhaps it would be easier to look how the end results looks like in this PR's branch: https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis/tree/write-main-readme

**Comment by shukapoo** [comment]
Thanks a lot Kirill!
It looks very good & well arranged on a quick view, I’ll review it asap.

—
Shubham

**Review by kauralasoo — APPROVED** [review]
Thanks, Kirill! Looks good to me.

Kaur

**Comment by shukapoo** [comment]
LGTM aswell! Merging

**Pull request merged**
